# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "github.com/havoc-io/mutagen"
  version = "v0.7.0-beta2"

# [[constraint]]
#   branch = "master"
#   name = "k8s.io/api"

# [[constraint]]
#   name = "k8s.io/client-go"
#   branch = "release-8.0"

# [[constraint]]
#   name = "k8s.io/apimachinery"
#   revision = "488889b0007f63ffee90b66a34a2deca9ec58774"

[prune]
  go-tests = true
  unused-packages = true
